import SessionWrapper from "./Components/SessionWrapper";

import Footer from "./Components/SectionOne/Footer";
import NavBar from "./Components/SectionOne/NavBar";
import "./globals.css";

export const metadata = {
  title: "Ashu Meditation",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionWrapper>
          <NavBar />
          {children}
          <Footer />
        </SessionWrapper>
      </body>
    </html>
  );
}
